/**
 * Single source of truth for the HTTP security headers.
 * The build writes them out as:
 *   dist/_headers   (Netlify, Cloudflare Pages)
 *   dist/.htaccess  (Apache / cPanel hosting)
 * Change the policy here, then run `npm run build`.
 */

const SITE_CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "media-src 'none'",
  "object-src 'none'",
  "frame-src 'none'",
  "worker-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

// The editor at /admin/ loads Decap CMS and the identity widget from pinned,
// integrity-checked CDN URLs and talks to the host's identity/git-gateway
// endpoints on the same origin (plus GitHub if that backend is used later).
const ADMIN_CSP = [
  "default-src 'self'",
  "script-src 'self' https://unpkg.com https://identity.netlify.com",
  "style-src 'self' 'unsafe-inline' https://unpkg.com https://fonts.googleapis.com",
  "img-src 'self' data: blob: https:",
  "font-src 'self' data: https://fonts.gstatic.com",
  "connect-src 'self' https://*.netlify.com https://api.github.com https://api.netlify.com https://unpkg.com",
  "frame-src 'self' https://identity.netlify.com",
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

export const COMMON = {
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
  'X-Permitted-Cross-Domain-Policies': 'none',
};

export const SITE = { ...COMMON, 'Content-Security-Policy': SITE_CSP };
export const ADMIN = {
  ...COMMON,
  'Content-Security-Policy': ADMIN_CSP,
  'Cache-Control': 'no-store',
  'X-Robots-Tag': 'noindex, nofollow',
};
export const STATIC_ASSETS = { 'Cache-Control': 'public, max-age=31536000, immutable' };

/* ---- Netlify / Cloudflare Pages `_headers` ---- */
export function netlifyHeaders() {
  const block = (path, h) => `${path}\n` + Object.entries(h).map(([k, v]) => `  ${k}: ${v}`).join('\n') + '\n';
  return [
    '# Generated by scripts/security-headers.mjs — edit that file, not this one.',
    block('/*', SITE),
    block('/admin/*', ADMIN),
    block('/assets/*', STATIC_ASSETS),
  ].join('\n');
}

/* ---- Apache `.htaccess` ---- */
export function htaccess() {
  const set = (h) => Object.entries(h).map(([k, v]) => `    Header always set ${k} "${v.replace(/"/g, '\\"')}"`).join('\n');
  return `# Generated by scripts/security-headers.mjs — edit that file, not this one.
Options -Indexes -MultiViews
ServerSignature Off

# Block access to anything that is not meant to be public (defence in depth;
# the dist/ folder should not contain these in the first place)
<FilesMatch "(^\\.|\\.(md|yml|yaml|toml|json|lock|mjs|map|log|sh|env)$)">
    Require all denied
</FilesMatch>
<FilesMatch "^(robots\\.txt|sitemap\\.xml|index\\.json|config\\.yml|site\\.webmanifest)$">
    Require all granted
</FilesMatch>
RedirectMatch 404 /\\.git

# Force HTTPS
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

<IfModule mod_headers.c>
${set(SITE)}
    <If "%{REQUEST_URI} =~ m#^/admin/#">
${set(ADMIN)}
    </If>
    <If "%{REQUEST_URI} =~ m#^/assets/#">
${set(STATIC_ASSETS)}
    </If>
</IfModule>

# Password-protect the editor at the web-server level as a second layer.
# Create the file with:  npm run hash-password   and store it OUTSIDE public_html.
# <If "%{REQUEST_URI} =~ m#^/admin/#">
#     AuthType Basic
#     AuthName "Quantact Partners admin"
#     AuthUserFile /home/<account>/.htpasswd
#     Require valid-user
# </If>

<IfModule mod_mime.c>
    AddType font/woff2 .woff2
    AddType application/manifest+json .webmanifest
</IfModule>
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json image/svg+xml
</IfModule>
`;
}
