/**
 * Single source of truth for the HTTP security headers.
 * The build writes them into dist/.htaccess (LiteSpeed / Apache, as used by
 * Hostinger shared hosting). Change the policy here, then run `npm run build`.
 */

const SITE_CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "media-src 'none'",
  "object-src 'none'",
  "frame-src 'none'",
  "worker-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

// The editor at /admin/ loads Decap CMS from a pinned, integrity-checked CDN
// URL, signs in through our own PHP OAuth relay and then talks to the GitHub
// API directly from the browser.
const ADMIN_CSP = [
  "default-src 'self'",
  "script-src 'self' https://unpkg.com",
  "style-src 'self' 'unsafe-inline' https://unpkg.com https://fonts.googleapis.com",
  "img-src 'self' data: blob: https:",
  "font-src 'self' data: https://fonts.gstatic.com",
  "connect-src 'self' https://api.github.com https://raw.githubusercontent.com https://unpkg.com",
  "frame-src 'self'",
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self' https://github.com",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

export const COMMON = {
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()',
  'Cross-Origin-Opener-Policy': 'same-origin-allow-popups',
  'Cross-Origin-Resource-Policy': 'same-origin',
  'X-Permitted-Cross-Domain-Policies': 'none',
};

export const SITE = { ...COMMON, 'Content-Security-Policy': SITE_CSP };
export const ADMIN = {
  ...COMMON,
  'Content-Security-Policy': ADMIN_CSP,
  'Cache-Control': 'no-store',
  'X-Robots-Tag': 'noindex, nofollow',
};
export const STATIC_ASSETS = { 'Cache-Control': 'public, max-age=31536000, immutable' };

const q = (v) => v.replace(/"/g, '\\"');

/* ---- Apache / LiteSpeed `.htaccess` (Hostinger) ---- */
export function htaccess() {
  const setAll = (h, cond) => Object.entries(h).map(([k, v]) => `    Header always set ${k} "${q(v)}"${cond ? ' ' + cond : ''}`).join('\n');
  return `# Generated by scripts/security-headers.mjs — edit that file, not this one.
# Target: Hostinger shared hosting (LiteSpeed, Apache-compatible).

DirectoryIndex index.html index.php
Options -Indexes -MultiViews
ServerSignature Off

# ---- Force HTTPS and a single canonical host (www → keep as served) ----
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteCond %{HTTP:X-Forwarded-Proto} !=https
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

# ---- Block anything that must never be served ----
RedirectMatch 404 /\\.git
<FilesMatch "^\\.">
    Require all denied
</FilesMatch>
<FilesMatch "\\.(md|yaml|toml|lock|mjs|map|log|sh|env|sql|bak|ini|example\\.php)$">
    Require all denied
</FilesMatch>
<FilesMatch "^(config\\.php|_lib\\.php|_headers|package\\.json|package-lock\\.json|composer\\.json)$">
    Require all denied
</FilesMatch>
# Explicitly public data files
<FilesMatch "^(robots\\.txt|sitemap\\.xml|index\\.json|config\\.yml|site\\.webmanifest)$">
    Require all granted
</FilesMatch>

# ---- Security headers ----
<IfModule mod_setenvif.c>
    SetEnvIf Request_URI "^/admin/" QP_ADMIN=1
    SetEnvIf Request_URI "^/assets/" QP_ASSET=1
</IfModule>
<IfModule mod_headers.c>
${setAll(COMMON)}
    Header always set Content-Security-Policy "${q(SITE_CSP)}" env=!QP_ADMIN
    Header always set Content-Security-Policy "${q(ADMIN_CSP)}" env=QP_ADMIN
    Header always set Cache-Control "no-store" env=QP_ADMIN
    Header always set X-Robots-Tag "noindex, nofollow" env=QP_ADMIN
    Header always set Cache-Control "public, max-age=31536000, immutable" env=QP_ASSET
    Header unset X-Powered-By
    Header unset Server
</IfModule>

# ---- Optional second lock on the editor (web-server password) ----
# 1. npm run hash-password   → copy the ".htpasswd line"
# 2. Save it to /home/<account>/domains/<domain>/private/.htpasswd
# 3. Uncomment and fix the path below.
# <IfModule mod_auth_basic.c>
#     SetEnvIf Request_URI "^/admin/" QP_NEED_AUTH=1
#     AuthType Basic
#     AuthName "Quantact Partners admin"
#     AuthUserFile /home/<account>/domains/<domain>/private/.htpasswd
#     <RequireAny>
#         Require env !QP_NEED_AUTH
#         Require valid-user
#     </RequireAny>
# </IfModule>

# ---- Types and compression ----
<IfModule mod_mime.c>
    AddType font/woff2 .woff2
    AddType application/manifest+json .webmanifest
    AddType image/svg+xml .svg
</IfModule>
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/css text/plain application/javascript application/json image/svg+xml font/woff2
</IfModule>
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType text/html "access plus 0 seconds"
    ExpiresByType text/css "access plus 1 year"
    ExpiresByType application/javascript "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType font/woff2 "access plus 1 year"
</IfModule>

# ---- Clean 404 ----
ErrorDocument 404 /index.html
`;
}
